server:
  port: "8090"
  mode: "debug"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "123456"
  dbname: "jd_take_out"
  sslmode: "disable"

jwt:
  secret: "jd-take-out-secret-key-2025"
  expire: 24

redis:
  host: "localhost"
  port: "6379"
  password: ""
  db: 0